import { Hono } from "hono";
import { federation } from "@fedify/hono";
import { Federation } from "./federation.ts";
import { UsersRouter } from "./adaptor/routes/usersRouter.tsx";
import { SignUpRouter } from "./adaptor/routes/signUpRouter.tsx";
import { SignInRouter } from "./adaptor/routes/signInRouter.tsx";
import { PostsRouter } from "./adaptor/routes/postsRouter.tsx";
import { FollowRouter } from "./adaptor/routes/followRouter.tsx";
import { HomeRouter } from "./adaptor/routes/homeRouter.tsx";
import { RemoteUsersRouter } from "./adaptor/routes/remoteUsersRouter.tsx";
import { LikeRouter } from "./adaptor/routes/likeRouter.tsx";
import { APIRouter } from "./adaptor/routes/apiRouter.tsx";
import { serveStatic } from "@hono/node-server/serve-static";

const app = new Hono();
const fed = Federation.getInstance();
app.use(federation(fed, () => undefined));
app.use("/static/*", serveStatic({ root: "./" }));
app.use("/favicon.ico", serveStatic({ path: "./favicon.ico" }));
app.get("/authorize_interaction", (c) => {
  const url = new URL(String(c.req.url));
  url.pathname = "/follow";
  return c.redirect(url);
});
app.get("/health", (c) => c.text("OK"));
app.route("/", HomeRouter);
app.route("/api", APIRouter);
app.route("/users", UsersRouter);
app.route("/remote-users", RemoteUsersRouter);
app.route("/posts", PostsRouter);
app.route("/sign-up", SignUpRouter);
app.route("/sign-in", SignInRouter);
app.route("/follow", FollowRouter);
app.route("/like", LikeRouter);
export default app;
