import { federation } from '@fedify/hono';
import { serveStatic } from '@hono/node-server/serve-static';
import { Hono } from 'hono';

import { APIRouter } from './adaptor/routes/apiRouter.tsx';
import { FollowRouter } from './adaptor/routes/followRouter.tsx';
import { HomeRouter } from './adaptor/routes/homeRouter.tsx';
import { LikeRouter } from './adaptor/routes/likeRouter.tsx';
import { NotificationRouter } from './adaptor/routes/notificationRouter.tsx';
import { PostsRouter } from './adaptor/routes/postsRouter.tsx';
import { PushSubscriptionRouter } from './adaptor/routes/pushSubscriptionRouter.tsx';
import { RemoteUsersRouter } from './adaptor/routes/remoteUsersRouter.tsx';
import { SignInRouter } from './adaptor/routes/signInRouter.tsx';
import { SignUpRouter } from './adaptor/routes/signUpRouter.tsx';
import { UsersRouter } from './adaptor/routes/usersRouter.tsx';
import { Federation } from './federation.ts';

const app = new Hono();
const fed = Federation.getInstance();
app.use(federation(fed, () => undefined));
app.use('/static/*', serveStatic({ root: './' }));
app.use('/favicon.ico', serveStatic({ path: './favicon.ico' }));
app.use('/sw.js', serveStatic({ path: './sw.js' }));
app.get('/authorize_interaction', (c) => {
  const url = new URL(String(c.req.url));
  url.pathname = '/follow';
  return c.redirect(url);
});
app.get('/health', (c) => c.text('OK'));
app.route('/', HomeRouter);
app.route('/api', APIRouter);
app.route('/api', PushSubscriptionRouter);
app.route('/users', UsersRouter);
app.route('/remote-users', RemoteUsersRouter);
app.route('/posts', PostsRouter);
app.route('/sign-up', SignUpRouter);
app.route('/sign-in', SignInRouter);
app.route('/follow', FollowRouter);
app.route('/like', LikeRouter);
app.route('/notifications', NotificationRouter);
export default app;
